[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = *

[[redirects]]
  from = "create"
  to = "https://mytimeline-calendar.herokuapp.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "reminder"
  to = "https://mytimeline-calendar.herokuapp.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "edit/*"
  to = "https://mytimeline-calendar.herokuapp.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "delete/*"
  to = "https://mytimeline-calendar.herokuapp.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "events"
  to = "https://mytimeline-calendar.herokuapp.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "delete-repeated/*"
  to = "https://mytimeline-calendar.herokuapp.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}


  

  

  

  